// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicContentHome,
  DefaultContentHomeProps
} from "./plasmic/17_s_business_portfolio_website/PlasmicContentHome";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface ContentHomeProps extends Omit<DefaultContentHomeProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultContentHomeProps altogether and have
// total control over the props for your component.
export interface ContentHomeProps extends DefaultContentHomeProps {}

function ContentHome_(props: ContentHomeProps, ref: HTMLElementRefOf<"div">) {
  // Use PlasmicContentHome to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicContentHome are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all ContentHomeProps here, but feel free
  // to do whatever works for you.

  return <PlasmicContentHome homeBody={{ ref }} {...props} />;
}

const ContentHome = React.forwardRef(ContentHome_);
export default ContentHome;
